a_centralwidget = QWidget()
                a_centralwidget.setObjectName("a_centralwidget")
                gridLayout_2 = QGridLayout(a_centralwidget)
                gridLayout_2.setObjectName("gridLayout_2")
                a_horizontalLayout = QHBoxLayout()
                a_horizontalLayout.setObjectName("a_horizontalLayout")
                a_label = QLabel(a_centralwidget)
                a_label.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label.setAlignment(Qt.AlignCenter)
                a_label.setObjectName("a_label")
                a_horizontalLayout.addWidget(a_label)
                a_lineEdit = QLineEdit(a_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(a_lineEdit.sizePolicy().hasHeightForWidth())
                a_lineEdit.setSizePolicy(sizePolicy)
                a_lineEdit.setMinimumSize(QSize(0, 0))
                a_lineEdit.setStyleSheet("")
                a_lineEdit.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
                a_lineEdit.setReadOnly(True)
                a_lineEdit.setObjectName("a_lineEdit")
                a_horizontalLayout.addWidget(a_lineEdit)
                a_pushButton = QPushButton(a_centralwidget)
                a_pushButton.setObjectName("a_pushButton")
                a_horizontalLayout.addWidget(a_pushButton)
                a_pushButton_2 = QPushButton(a_centralwidget)
                a_pushButton_2.setObjectName("a_pushButton_2")
                a_horizontalLayout.addWidget(a_pushButton_2)
                gridLayout_2.addLayout(a_horizontalLayout, 0, 0, 1, 1)
                a_horizontalLayout_2 = QHBoxLayout()
                a_horizontalLayout_2.setObjectName("a_horizontalLayout_2")
                a_label_2 = QLabel(a_centralwidget)
                a_label_2.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_2.setAlignment(Qt.AlignCenter)
                a_label_2.setObjectName("a_label_2")
                a_horizontalLayout_2.addWidget(a_label_2)
                a_lineEdit_2 = QLineEdit(a_centralwidget)
                a_lineEdit_2.setAlignment(Qt.AlignCenter)
                a_lineEdit_2.setReadOnly(True)
                a_lineEdit_2.setObjectName("a_lineEdit_2")
                a_horizontalLayout_2.addWidget(a_lineEdit_2)
                a_label_3 = QLabel(a_centralwidget)
                a_label_3.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_3.setAlignment(Qt.AlignCenter)
                a_label_3.setObjectName("a_label_3")
                a_horizontalLayout_2.addWidget(a_label_3)
                a_lineEdit_3 = QLineEdit(a_centralwidget)
                a_lineEdit_3.setAlignment(Qt.AlignCenter)
                a_lineEdit_3.setReadOnly(True)
                a_lineEdit_3.setObjectName("a_lineEdit_3")
                a_horizontalLayout_2.addWidget(a_lineEdit_3)
                a_label_4 = QLabel(a_centralwidget)
                a_label_4.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_4.setAlignment(Qt.AlignCenter)
                a_label_4.setObjectName("a_label_4")
                a_horizontalLayout_2.addWidget(a_label_4)
                a_lineEdit_4 = QLineEdit(a_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(a_lineEdit_4.sizePolicy().hasHeightForWidth())
                a_lineEdit_4.setSizePolicy(sizePolicy)
                a_lineEdit_4.setAlignment(Qt.AlignCenter)
                a_lineEdit_4.setReadOnly(True)
                a_lineEdit_4.setObjectName("a_lineEdit_4")
                a_horizontalLayout_2.addWidget(a_lineEdit_4)
                a_label_12 = QLabel(a_centralwidget)
                a_label_12.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_12.setAlignment(Qt.AlignCenter)
                a_label_12.setObjectName("a_label_12")
                a_horizontalLayout_2.addWidget(a_label_12)
                a_lineEdit_12 = QLineEdit(a_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(a_lineEdit_12.sizePolicy().hasHeightForWidth())
                a_lineEdit_12.setSizePolicy(sizePolicy)
                a_lineEdit_12.setAlignment(Qt.AlignCenter)
                a_lineEdit_12.setReadOnly(True)
                a_lineEdit_12.setObjectName("a_lineEdit_12")
                a_horizontalLayout_2.addWidget(a_lineEdit_12)
                a_label_5 = QLabel(a_centralwidget)
                a_label_5.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_5.setAlignment(Qt.AlignCenter)
                a_label_5.setObjectName("a_label_5")
                a_horizontalLayout_2.addWidget(a_label_5)
                a_lineEdit_5 = QLineEdit(a_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(a_lineEdit_5.sizePolicy().hasHeightForWidth())
                a_lineEdit_5.setSizePolicy(sizePolicy)
                a_lineEdit_5.setAlignment(Qt.AlignCenter)
                a_lineEdit_5.setReadOnly(True)
                a_lineEdit_5.setObjectName("a_lineEdit_5")
                a_horizontalLayout_2.addWidget(a_lineEdit_5)
                gridLayout_2.addLayout(a_horizontalLayout_2, 1, 0, 1, 1)
                a_horizontalLayout_3 = QHBoxLayout()
                a_horizontalLayout_3.setObjectName("a_horizontalLayout_3")
                a_label_11 = QLabel(a_centralwidget)
                a_label_11.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_11.setAlignment(Qt.AlignCenter)
                a_label_11.setObjectName("a_label_11")
                a_horizontalLayout_3.addWidget(a_label_11)
                a_lineEdit_11 = QLineEdit(a_centralwidget)
                a_lineEdit_11.setAlignment(Qt.AlignCenter)
                a_lineEdit_11.setReadOnly(True)
                a_lineEdit_11.setObjectName("a_lineEdit_11")
                a_horizontalLayout_3.addWidget(a_lineEdit_11)
                a_label_6 = QLabel(a_centralwidget)
                a_label_6.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_6.setAlignment(Qt.AlignCenter)
                a_label_6.setObjectName("a_label_6")
                a_horizontalLayout_3.addWidget(a_label_6)
                a_lineEdit_6 = QLineEdit(a_centralwidget)
                a_lineEdit_6.setAlignment(Qt.AlignCenter)
                a_lineEdit_6.setReadOnly(True)
                a_lineEdit_6.setObjectName("a_lineEdit_6")
                a_horizontalLayout_3.addWidget(a_lineEdit_6)
                a_label_7 = QLabel(a_centralwidget)
                a_label_7.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_7.setAlignment(Qt.AlignCenter)
                a_label_7.setObjectName("a_label_7")
                a_horizontalLayout_3.addWidget(a_label_7)
                a_lineEdit_7 = QLineEdit(a_centralwidget)
                a_lineEdit_7.setAlignment(Qt.AlignCenter)
                a_lineEdit_7.setReadOnly(True)
                a_lineEdit_7.setObjectName("a_lineEdit_7")
                a_horizontalLayout_3.addWidget(a_lineEdit_7)
                a_label_8 = QLabel(a_centralwidget)
                a_label_8.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_8.setAlignment(Qt.AlignCenter)
                a_label_8.setObjectName("a_label_8")
                a_horizontalLayout_3.addWidget(a_label_8)
                a_lineEdit_8 = QLineEdit(a_centralwidget)
                a_lineEdit_8.setAlignment(Qt.AlignCenter)
                a_lineEdit_8.setReadOnly(True)
                a_lineEdit_8.setObjectName("a_lineEdit_8")
                a_horizontalLayout_3.addWidget(a_lineEdit_8)
                a_label_9 = QLabel(a_centralwidget)
                a_label_9.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_9.setAlignment(Qt.AlignCenter)
                a_label_9.setObjectName("a_label_9")
                a_horizontalLayout_3.addWidget(a_label_9)
                a_lineEdit_9 = QLineEdit(a_centralwidget)
                a_lineEdit_9.setAlignment(Qt.AlignCenter)
                a_lineEdit_9.setReadOnly(True)
                a_lineEdit_9.setObjectName("a_lineEdit_9")
                a_horizontalLayout_3.addWidget(a_lineEdit_9)
                a_label_10 = QLabel(a_centralwidget)
                a_label_10.setStyleSheet("margin-left : 5px;\n"
                "margin-right : 5px;\n"
                "")
                a_label_10.setAlignment(Qt.AlignCenter)
                a_label_10.setObjectName("a_label_10")
                a_horizontalLayout_3.addWidget(a_label_10)
                a_lineEdit_10 = QLineEdit(a_centralwidget)
                a_lineEdit_10.setAlignment(Qt.AlignCenter)
                a_lineEdit_10.setReadOnly(True)
                a_lineEdit_10.setObjectName("a_lineEdit_10")
                a_horizontalLayout_3.addWidget(a_lineEdit_10)
                gridLayout_2.addLayout(a_horizontalLayout_3, 2, 0, 1, 1)
                gridLayout = QGridLayout()
                gridLayout.setObjectName("gridLayout")
                label = QLabel(a_centralwidget)
                label.setText("")
                label.setObjectName("label")
                gridLayout.addWidget(label, 0, 1, 1, 1)
                spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
                gridLayout.addItem(spacerItem, 1, 1, 1, 1)
                pushButton = QPushButton(a_centralwidget)
                pushButton.setObjectName("pushButton")
                gridLayout.addWidget(pushButton, 2, 1, 1, 1)
                a_tableWidget = QTableWidget(a_centralwidget)
                a_tableWidget.setObjectName("a_tableWidget")
                a_tableWidget.setColumnCount(0)
                a_tableWidget.setRowCount(0)
                gridLayout.addWidget(a_tableWidget, 0, 0, 3, 1)
                gridLayout.setColumnStretch(0, 3)
                gridLayout.setColumnStretch(1, 2)
                gridLayout.setRowStretch(0, 1)
                gridLayout.setRowStretch(1, 1)
                gridLayout_2.addLayout(gridLayout, 3, 0, 1, 1)

                _translate = QCoreApplication.translate
                a_label.setText(_translate("MainWindow", "작업지시서 저장 경로"))
                a_pushButton.setText(_translate("MainWindow", "폴더 열기"))
                a_pushButton_2.setText(_translate("MainWindow", "닫기"))
                a_label_2.setText(_translate("MainWindow", "관리번호"))
                a_label_3.setText(_translate("MainWindow", "작업지시일"))
                a_label_4.setText(_translate("MainWindow", "전개완료일"))
                a_label_12.setText(_translate("MainWindow", "프레임완료일"))
                a_label_5.setText(_translate("MainWindow", "판금완료일"))
                a_label_11.setText(_translate("MainWindow", "FRAME"))
                a_label_6.setText(_translate("MainWindow", "SPCC"))
                a_label_7.setText(_translate("MainWindow", "SUS"))
                a_label_8.setText(_translate("MainWindow", "AL"))
                a_label_9.setText(_translate("MainWindow", "기타"))
                a_label_10.setText(_translate("MainWindow", "잔여시간"))
                pushButton.setText(_translate("MainWindow", "색인"))