MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 270)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(350, 270))
        MainWindow.setMaximumSize(QSize(350, 270))
        centralwidget = QWidget(MainWindow)
        centralwidget.setObjectName("centralwidget")
        gridLayout = QGridLayout(centralwidget)
        gridLayout.setContentsMargins(15, 15, 15, 15)
        gridLayout.setObjectName("gridLayout")
        verticalLayout = QVBoxLayout()
        verticalLayout.setObjectName("verticalLayout")
        label = QLabel(centralwidget)
        label.setAlignment(Qt.AlignCenter)
        label.setObjectName("label")
        verticalLayout.addWidget(label)
        horizontalLayout_2 = QHBoxLayout()
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        lineEdit = QLineEdit(centralwidget)
        lineEdit.setMinimumSize(QSize(90, 0))
        lineEdit.setMaximumSize(QSize(90, 16777215))
        lineEdit.setAlignment(Qt.AlignCenter)
        lineEdit.setObjectName("lineEdit")
        horizontalLayout_2.addWidget(lineEdit)
        pushButton_3 = QPushButton(centralwidget)
        pushButton_3.setMinimumSize(QSize(20, 20))
        pushButton_3.setMaximumSize(QSize(20, 20))
        pushButton_3.setObjectName("pushButton_3")
        horizontalLayout_2.addWidget(pushButton_3)
        label_2 = QLabel(centralwidget)
        label_2.setObjectName("label_2")
        horizontalLayout_2.addWidget(label_2)
        lineEdit_2 = QLineEdit(centralwidget)
        lineEdit_2.setMinimumSize(QSize(90, 0))
        lineEdit_2.setMaximumSize(QSize(90, 16777215))
        lineEdit_2.setAlignment(Qt.AlignCenter)
        lineEdit_2.setObjectName("lineEdit_2")
        horizontalLayout_2.addWidget(lineEdit_2)
        pushButton_4 = QPushButton(centralwidget)
        pushButton_4.setMinimumSize(QSize(20, 20))
        pushButton_4.setMaximumSize(QSize(20, 20))
        pushButton_4.setObjectName("pushButton_4")
        horizontalLayout_2.addWidget(pushButton_4)
        pushButton_5 = QPushButton(centralwidget)
        pushButton_5.setMinimumSize(QSize(50, 20))
        pushButton_5.setMaximumSize(QSize(50, 20))
        pushButton_5.setObjectName("pushButton_5")
        horizontalLayout_2.addWidget(pushButton_5)
        verticalLayout.addLayout(horizontalLayout_2)
        tableWidget = QTableWidget(centralwidget)
        tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        tableWidget.setAlternatingRowColors(True)
        tableWidget.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        tableWidget.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        tableWidget.setObjectName("tableWidget")
        tableWidget.setColumnCount(0)
        tableWidget.setRowCount(0)
        tableWidget.verticalHeader().setVisible(False)
        verticalLayout.addWidget(tableWidget)
        horizontalLayout = QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        horizontalLayout.addItem(spacerItem)
        pushButton = QPushButton(centralwidget)
        pushButton.setObjectName("pushButton")
        horizontalLayout.addWidget(pushButton)
        verticalLayout.addLayout(horizontalLayout)
        gridLayout.addLayout(verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(centralwidget)

        QMetaObject.connectSlotsByName(MainWindow)

        _translate = QCoreApplication.translate
        label.setText(_translate("MainWindow", "관리번호"))
        lineEdit.setInputMask(_translate("MainWindow", "0000-00-00"))
        pushButton_3.setText(_translate("MainWindow", "▼"))
        label_2.setText(_translate("MainWindow", "~"))
        lineEdit_2.setInputMask(_translate("MainWindow", "0000-00-00"))
        pushButton_4.setText(_translate("MainWindow", "▼"))
        pushButton_5.setText(_translate("MainWindow", "검색"))
        pushButton.setText(_translate("MainWindow", "다음"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
