c_centralwidget = QWidget()
                c_centralwidget.setObjectName("c_centralwidget")
                gridLayout = QGridLayout(c_centralwidget)
                gridLayout.setObjectName("gridLayout")
                c_tableWidget_2 = QTableWidget(c_centralwidget)
                c_tableWidget_2.setEditTriggers(QAbstractItemView.NoEditTriggers)
                c_tableWidget_2.setDragDropMode(QAbstractItemView.NoDragDrop)
                c_tableWidget_2.setSelectionBehavior(QAbstractItemView.SelectRows)
                c_tableWidget_2.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
                c_tableWidget_2.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
                c_tableWidget_2.setObjectName("c_tableWidget_2")
                c_tableWidget_2.setColumnCount(0)
                c_tableWidget_2.setRowCount(0)
                c_tableWidget_2.verticalHeader().setVisible(False)
                gridLayout.addWidget(c_tableWidget_2, 2, 0, 2, 1)
                c_horizontalLayout_2 = QHBoxLayout()
                c_horizontalLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
                c_horizontalLayout_2.setObjectName("c_horizontalLayout_2")
                c_label = QLabel(c_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(c_label.sizePolicy().hasHeightForWidth())
                c_label.setSizePolicy(sizePolicy)
                c_label.setObjectName("c_label")
                c_horizontalLayout_2.addWidget(c_label)
                c_comboBox = QComboBox(c_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(c_comboBox.sizePolicy().hasHeightForWidth())
                c_comboBox.setSizePolicy(sizePolicy)
                c_comboBox.setMinimumSize(QSize(100, 0))
                font = QFont()
                font.setPointSize(12)
                c_comboBox.setFont(font)
                c_comboBox.setObjectName("c_comboBox")
                c_horizontalLayout_2.addWidget(c_comboBox)
                c_label_2 = QLabel(c_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(c_label_2.sizePolicy().hasHeightForWidth())
                c_label_2.setSizePolicy(sizePolicy)
                c_label_2.setObjectName("c_label_2")
                c_horizontalLayout_2.addWidget(c_label_2)
                c_lineEdit_2 = QLineEdit(c_centralwidget)
                c_lineEdit_2.setObjectName("c_lineEdit_2")
                c_horizontalLayout_2.addWidget(c_lineEdit_2)
                c_pushButton_3 = QPushButton(c_centralwidget)
                c_pushButton_3.setObjectName("c_pushButton_3")
                c_horizontalLayout_2.addWidget(c_pushButton_3)
                gridLayout.addLayout(c_horizontalLayout_2, 0, 0, 1, 1)
                c_label_4 = QLabel(c_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(c_label_4.sizePolicy().hasHeightForWidth())
                c_label_4.setSizePolicy(sizePolicy)
                c_label_4.setAlignment(Qt.AlignCenter)
                c_label_4.setObjectName("c_label_4")
                gridLayout.addWidget(c_label_4, 1, 2, 1, 1)
                label = QLabel(c_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
                label.setSizePolicy(sizePolicy)
                label.setText("")
                label.setObjectName("label")
                gridLayout.addWidget(label, 4, 0, 1, 1)
                c_label_3 = QLabel(c_centralwidget)
                sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(c_label_3.sizePolicy().hasHeightForWidth())
                c_label_3.setSizePolicy(sizePolicy)
                c_label_3.setAlignment(Qt.AlignCenter)
                c_label_3.setObjectName("c_label_3")
                gridLayout.addWidget(c_label_3, 1, 0, 1, 1)
                horizontalLayout = QHBoxLayout()
                horizontalLayout.setObjectName("horizontalLayout")
                spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
                horizontalLayout.addItem(spacerItem)
                pushButton_4 = QPushButton(c_centralwidget)
                pushButton_4.setFlat(True)
                pushButton_4.setObjectName("pushButton_4")
                horizontalLayout.addWidget(pushButton_4)
                pushButton = QPushButton(c_centralwidget)
                pushButton.setObjectName("pushButton")
                horizontalLayout.addWidget(pushButton)
                pushButton_2 = QPushButton(c_centralwidget)
                pushButton_2.setObjectName("pushButton_2")
                horizontalLayout.addWidget(pushButton_2)
                gridLayout.addLayout(horizontalLayout, 0, 2, 1, 1)
                pushButton_3 = QPushButton(c_centralwidget)
                pushButton_3.setObjectName("pushButton_3")
                gridLayout.addWidget(pushButton_3, 5, 0, 1, 1)
                c_verticalLayout = QVBoxLayout()
                c_verticalLayout.setSpacing(6)
                c_verticalLayout.setObjectName("c_verticalLayout")
                spacerItem1 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
                c_verticalLayout.addItem(spacerItem1)
                c_pushButton = QPushButton(c_centralwidget)
                c_pushButton.setMinimumSize(QSize(50, 50))
                c_pushButton.setMaximumSize(QSize(50, 50))
                c_pushButton.setObjectName("c_pushButton")
                c_verticalLayout.addWidget(c_pushButton)
                c_pushButton_2 = QPushButton(c_centralwidget)
                c_pushButton_2.setMinimumSize(QSize(50, 50))
                c_pushButton_2.setMaximumSize(QSize(50, 50))
                c_pushButton_2.setObjectName("c_pushButton_2")
                c_verticalLayout.addWidget(c_pushButton_2)
                spacerItem2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
                c_verticalLayout.addItem(spacerItem2)
                gridLayout.addLayout(c_verticalLayout, 0, 1, 6, 1)
                c_tableWidget = QTableWidget(c_centralwidget)
                c_tableWidget.setMaximumSize(QSize(16777211, 16777215))
                c_tableWidget.setEditTriggers(QAbstractItemView.AllEditTriggers)
                c_tableWidget.setDragDropMode(QAbstractItemView.NoDragDrop)
                c_tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
                c_tableWidget.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
                c_tableWidget.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
                c_tableWidget.setObjectName("c_tableWidget")
                c_tableWidget.setColumnCount(0)
                c_tableWidget.setRowCount(0)
                c_tableWidget.verticalHeader().setVisible(False)
                gridLayout.addWidget(c_tableWidget, 2, 2, 4, 1)
                gridLayout.setColumnStretch(0, 1)
                gridLayout.setColumnStretch(2, 2)
                gridLayout.setRowStretch(1, 1)
                gridLayout.setRowStretch(2, 1)
                gridLayout.setRowStretch(3, 1)
                gridLayout.setRowStretch(4, 2)
                widget.setLayout(gridLayout)
                _translate = QCoreApplication.translate
                c_label.setText(_translate("c_MainWindow", "업체명 : "))
                c_label_2.setText(_translate("c_MainWindow", "GEO 이름 : "))
                c_pushButton_3.setText(_translate("c_MainWindow", "검색"))
                c_label_4.setText(_translate("c_MainWindow", "등록 리스트"))
                c_label_3.setText(_translate("c_MainWindow", "검색 리스트"))
                pushButton_4.setText(_translate("c_MainWindow", "요청자 : "))
                pushButton.setText(_translate("c_MainWindow", "저장"))
                pushButton_2.setText(_translate("c_MainWindow", "닫기"))
                pushButton_3.setText(_translate("c_MainWindow", "색인"))
                c_pushButton.setText(_translate("c_MainWindow", "→"))
                c_pushButton_2.setText(_translate("c_MainWindow", "←"))