        gridLayout = QGridLayout(grid)
        gridLayout.setObjectName("gridLayout")
        hbox2 = QHBoxLayout()
        hbox2.setObjectName("hbox2")
        labels3 = QLabel(grid)
        labels3.setObjectName("labels3")
        hbox2.addWidget(labels3)
        line2 = QLineEdit(grid)
        line2.setMaximumSize(QSize(110, 20))
        line2.setAlignment(Qt.AlignCenter)
        line2.setObjectName("line2")
        hbox2.addWidget(line2)
        datebtn1 = QPushButton(grid)
        datebtn1.setMinimumSize(QSize(23, 23))
        datebtn1.setMaximumSize(QSize(23, 23))
        datebtn1.setObjectName("datebtn1")
        hbox2.addWidget(datebtn1)
        labels4 = QLabel(grid)
        labels4.setObjectName("labels4")
        hbox2.addWidget(labels4)
        line3 = QLineEdit(grid)
        line3.setMaximumSize(QSize(110, 20))
        line3.setAlignment(Qt.AlignCenter)
        line3.setObjectName("line3")
        hbox2.addWidget(line3)
        datebtn2 = QPushButton(grid)
        datebtn2.setMinimumSize(QSize(23, 23))
        datebtn2.setMaximumSize(QSize(23, 23))
        datebtn2.setObjectName("datebtn2")
        hbox2.addWidget(datebtn2)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        hbox2.addItem(spacerItem)
        labels3_2 = QLabel(grid)
        labels3_2.setObjectName("labels3_2")
        hbox2.addWidget(labels3_2)
        comboBox = QComboBox(grid)
        comboBox.setObjectName("comboBox")
        hbox2.addWidget(comboBox)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        hbox2.addItem(spacerItem1)
        label_5 = QLabel(grid)
        label_5.setObjectName("label_5")
        hbox2.addWidget(label_5)
        lineEdit_4 = QLineEdit(grid)
        lineEdit_4.setMaximumSize(QSize(200, 20))
        lineEdit_4.setObjectName("lineEdit_4")
        hbox2.addWidget(lineEdit_4)
        pushButton_7 = QPushButton(grid)
        pushButton_7.setObjectName("pushButton_7")
        hbox2.addWidget(pushButton_7)
        refreshbtn = QPushButton(grid)
        refreshbtn.setObjectName("refreshbtn")
        hbox2.addWidget(refreshbtn)
        gridLayout.addLayout(hbox2, 1, 0, 1, 2)
        table1 = QTableWidget(grid)
        table1.setObjectName("table1")
        table1.setColumnCount(0)
        table1.setRowCount(0)
        gridLayout.addWidget(table1, 2, 0, 1, 1)

        QMetaObject.connectSlotsByName(grid)

        _translate = QCoreApplication.translate
        labels3.setText(_translate("grid", "수주일자 : "))
        line2.setInputMask(_translate("grid", "0000 - 00 - 00"))
        datebtn1.setText(_translate("grid", "▼"))
        labels4.setText(_translate("grid", "~"))
        line3.setInputMask(_translate("grid", "0000 - 00 - 00"))
        datebtn2.setText(_translate("grid", "▼"))
        labels3_2.setText(_translate("grid", "거래처 : "))
        label_5.setText(_translate("grid", "도면번호 검색 : "))
        pushButton_7.setText(_translate("grid", "검색"))
        refreshbtn.setText(_translate("grid", "새로고침"))
        table1.setSortingEnabled(True)