        gridLayout = QGridLayout()
        gridLayout.setObjectName("gridLayout")
        hbox2 = QHBoxLayout()
        hbox2.setObjectName("hbox2")
        labels3 = QLabel()
        labels3.setObjectName("labels3")
        hbox2.addWidget(labels3)
        line2 = QLineEdit()
        line2.setMaximumSize(QSize(110, 20))
        line2.setAlignment(Qt.AlignCenter)
        line2.setObjectName("line2")
        hbox2.addWidget(line2)
        datebtn1 = QPushButton()
        datebtn1.setMinimumSize(QSize(23, 23))
        datebtn1.setMaximumSize(QSize(23, 23))
        datebtn1.setObjectName("datebtn1")
        hbox2.addWidget(datebtn1)
        labels4 = QLabel()
        labels4.setObjectName("labels4")
        hbox2.addWidget(labels4)
        line3 = QLineEdit()
        line3.setMaximumSize(QSize(110, 20))
        line3.setAlignment(Qt.AlignCenter)
        line3.setObjectName("line3")
        hbox2.addWidget(line3)
        datebtn2 = QPushButton()
        datebtn2.setMinimumSize(QSize(23, 23))
        datebtn2.setMaximumSize(QSize(23, 23))
        datebtn2.setObjectName("datebtn2")
        hbox2.addWidget(datebtn2)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        hbox2.addItem(spacerItem)
        label_5 = QLabel()
        label_5.setObjectName("label_5")
        hbox2.addWidget(label_5)
        lineEdit_4 = QLineEdit()
        lineEdit_4.setMaximumSize(QSize(200, 20))
        lineEdit_4.setObjectName("lineEdit_4")
        hbox2.addWidget(lineEdit_4)
        pushButton_7 = QPushButton()
        pushButton_7.setObjectName("pushButton_7")
        hbox2.addWidget(pushButton_7)
        refreshbtn = QPushButton()
        refreshbtn.setObjectName("refreshbtn")
        hbox2.addWidget(refreshbtn)
        gridLayout.addLayout(hbox2, 0, 0, 1, 1)
        table1 = QTableWidget()
        table1.setObjectName("table1")
        table1.setColumnCount(0)
        table1.setRowCount(0)
        gridLayout.addWidget(table1, 2, 0, 1, 1)
        hbox2_2 = QHBoxLayout()
        hbox2_2.setObjectName("hbox2_2")
        label = QLabel()
        label.setObjectName("label")
        hbox2_2.addWidget(label)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        hbox2_2.addItem(spacerItem1)
        pushButton_3 = QPushButton()
        pushButton_3.setObjectName("pushButton_3")
        hbox2_2.addWidget(pushButton_3)
        pushButton_2 = QPushButton()
        pushButton_2.setObjectName("pushButton_2")
        hbox2_2.addWidget(pushButton_2)
        gridLayout.addLayout(hbox2_2, 1, 0, 1, 1)

        _translate = QCoreApplication.translate
        labels3.setText(_translate("grid", "수주일자 : "))
        line2.setInputMask(_translate("grid", "0000 - 00 - 00"))
        datebtn1.setText(_translate("grid", "▼"))
        labels4.setText(_translate("grid", "~"))
        line3.setInputMask(_translate("grid", "0000 - 00 - 00"))
        datebtn2.setText(_translate("grid", "▼"))
        label_5.setText(_translate("grid", "도면번호 검색 : "))
        pushButton_7.setText(_translate("grid", "검색"))
        refreshbtn.setText(_translate("grid", "새로고침"))
        table1.setSortingEnabled(True)
        label.setText(_translate("grid", "필터 현황 : "))
        pushButton_3.setText(_translate("grid", "필터설정"))
        pushButton_2.setText(_translate("grid", "필터초기화"))