# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VPS_LABEL.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1113, 381)
        MainWindow.setMinimumSize(QtCore.QSize(1113, 381))
        MainWindow.setMaximumSize(QtCore.QSize(1113, 381))
        MainWindow.setStyleSheet("background-color: rgb(98, 102, 119);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(-6, -6, 1121, 381))
        self.gridFrame.setObjectName("gridFrame")
        self.date2_label = QtWidgets.QLabel(self.gridFrame)
        self.date2_label.setGeometry(QtCore.QRect(785, 40, 100, 30))
        self.date2_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.date2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date2_label.setObjectName("date2_label")
        self.path_create = QtWidgets.QPushButton(self.gridFrame)
        self.path_create.setGeometry(QtCore.QRect(673, 10, 50, 30))
        self.path_create.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 56, 100);\n"
"font: 75 10pt \"맑은 고딕\";\n"
"")
        self.path_create.setCheckable(False)
        self.path_create.setObjectName("path_create")
        self.campany = QtWidgets.QLineEdit(self.gridFrame)
        self.campany.setGeometry(QtCore.QRect(160, 40, 620, 30))
        self.campany.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";")
        self.campany.setText("")
        self.campany.setObjectName("campany")
        self.work_label = QtWidgets.QLabel(self.gridFrame)
        self.work_label.setGeometry(QtCore.QRect(10, 100, 150, 30))
        self.work_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.work_label.setAlignment(QtCore.Qt.AlignCenter)
        self.work_label.setObjectName("work_label")
        self.file_label = QtWidgets.QLabel(self.gridFrame)
        self.file_label.setGeometry(QtCore.QRect(10, 130, 150, 200))
        self.file_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.file_label.setAlignment(QtCore.Qt.AlignCenter)
        self.file_label.setObjectName("file_label")
        self.create = QtWidgets.QPushButton(self.gridFrame)
        self.create.setGeometry(QtCore.QRect(11, 330, 999, 30))
        self.create.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 56, 100);\n"
"font: 75 10pt \"맑은 고딕\";\n"
"")
        self.create.setObjectName("create")
        self.ea = QtWidgets.QLabel(self.gridFrame)
        self.ea.setGeometry(QtCore.QRect(885, 100, 230, 30))
        self.ea.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);")
        self.ea.setText("")
        self.ea.setObjectName("ea")
        self.name_label = QtWidgets.QLabel(self.gridFrame)
        self.name_label.setGeometry(QtCore.QRect(10, 70, 150, 30))
        self.name_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.work = QtWidgets.QLabel(self.gridFrame)
        self.work.setGeometry(QtCore.QRect(160, 100, 620, 30))
        self.work.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);")
        self.work.setText("")
        self.work.setObjectName("work")
        self.name = QtWidgets.QLineEdit(self.gridFrame)
        self.name.setGeometry(QtCore.QRect(160, 70, 620, 30))
        self.name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";")
        self.name.setObjectName("name")
        self.file_search = QtWidgets.QPushButton(self.gridFrame)
        self.file_search.setGeometry(QtCore.QRect(1012, 130, 102, 135))
        self.file_search.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 56, 100);\n"
"font: 75 10pt \"맑은 고딕\";\n"
"")
        self.file_search.setObjectName("file_search")
        self.path_label = QtWidgets.QLabel(self.gridFrame)
        self.path_label.setGeometry(QtCore.QRect(10, 10, 150, 30))
        self.path_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.path_label.setAlignment(QtCore.Qt.AlignCenter)
        self.path_label.setObjectName("path_label")
        self.prog = QtWidgets.QProgressBar(self.gridFrame)
        self.prog.setGeometry(QtCore.QRect(10, 367, 1011, 10))
        self.prog.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 1pt \"맑은 고딕\";\n"
"")
        self.prog.setProperty("value", 0)
        self.prog.setObjectName("prog")
        self.date2 = QtWidgets.QLineEdit(self.gridFrame)
        self.date2.setGeometry(QtCore.QRect(885, 40, 200, 30))
        self.date2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";")
        self.date2.setText("")
        self.date2.setObjectName("date2")
        self.filelist = QtWidgets.QListWidget(self.gridFrame)
        self.filelist.setGeometry(QtCore.QRect(160, 130, 852, 200))
        self.filelist.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";")
        self.filelist.setObjectName("filelist")
        self.date1_label = QtWidgets.QLabel(self.gridFrame)
        self.date1_label.setGeometry(QtCore.QRect(785, 10, 100, 30))
        self.date1_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.date1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date1_label.setObjectName("date1_label")
        self.ea_label = QtWidgets.QLabel(self.gridFrame)
        self.ea_label.setGeometry(QtCore.QRect(785, 100, 100, 30))
        self.ea_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.ea_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ea_label.setObjectName("ea_label")
        self.path_save = QtWidgets.QPushButton(self.gridFrame)
        self.path_save.setGeometry(QtCore.QRect(728, 10, 50, 30))
        self.path_save.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 56, 100);\n"
"font: 75 10pt \"맑은 고딕\";\n"
"")
        self.path_save.setObjectName("path_save")
        self.company_label = QtWidgets.QLabel(self.gridFrame)
        self.company_label.setGeometry(QtCore.QRect(10, 40, 150, 30))
        self.company_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.company_label.setAlignment(QtCore.Qt.AlignCenter)
        self.company_label.setObjectName("company_label")
        self.printbtn = QtWidgets.QPushButton(self.gridFrame)
        self.printbtn.setGeometry(QtCore.QRect(1012, 330, 102, 51))
        self.printbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 56, 100);\n"
"font: 75 10pt \"맑은 고딕\";\n"
"")
        self.printbtn.setObjectName("printbtn")
        self.date1 = QtWidgets.QLineEdit(self.gridFrame)
        self.date1.setGeometry(QtCore.QRect(885, 10, 200, 30))
        self.date1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";")
        self.date1.setText("")
        self.date1.setObjectName("date1")
        self.path = QtWidgets.QLabel(self.gridFrame)
        self.path.setGeometry(QtCore.QRect(160, 10, 510, 30))
        self.path.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";")
        self.path.setText("")
        self.path.setObjectName("path")
        self.allreset = QtWidgets.QPushButton(self.gridFrame)
        self.allreset.setGeometry(QtCore.QRect(1012, 298, 102, 30))
        self.allreset.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 56, 100);\n"
"font: 75 10pt \"맑은 고딕\";\n"
"")
        self.allreset.setObjectName("allreset")
        self.reset = QtWidgets.QPushButton(self.gridFrame)
        self.reset.setGeometry(QtCore.QRect(1012, 266, 102, 30))
        self.reset.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 56, 100);\n"
"font: 75 10pt \"맑은 고딕\";\n"
"")
        self.reset.setObjectName("reset")
        self.ea1 = QtWidgets.QRadioButton(self.gridFrame)
        self.ea1.setGeometry(QtCore.QRect(930, 105, 50, 20))
        self.ea1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.ea1.setObjectName("ea1")
        self.ea_group = QtWidgets.QButtonGroup(MainWindow)
        self.ea_group.setObjectName("ea_group")
        self.ea_group.addButton(self.ea1)
        self.ea2 = QtWidgets.QRadioButton(self.gridFrame)
        self.ea2.setGeometry(QtCore.QRect(1020, 105, 50, 20))
        self.ea2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.ea2.setObjectName("ea2")
        self.ea_group.addButton(self.ea2)
        self.date3_label = QtWidgets.QLabel(self.gridFrame)
        self.date3_label.setGeometry(QtCore.QRect(785, 70, 100, 30))
        self.date3_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";\n"
"")
        self.date3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date3_label.setObjectName("date3_label")
        self.date3 = QtWidgets.QLineEdit(self.gridFrame)
        self.date3.setGeometry(QtCore.QRect(885, 70, 200, 30))
        self.date3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"border: 2px solid rgb(127, 127, 127);\n"
"font: 10pt \"맑은 고딕\";")
        self.date3.setText("")
        self.date3.setObjectName("date3")
        self.date3_ex = QtWidgets.QPushButton(self.gridFrame)
        self.date3_ex.setGeometry(QtCore.QRect(1086, 70, 30, 30))
        self.date3_ex.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);")
        self.date3_ex.setObjectName("date3_ex")
        self.work1 = QtWidgets.QRadioButton(self.centralwidget)
        self.work1.setGeometry(QtCore.QRect(180, 99, 70, 20))
        self.work1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.work1.setObjectName("work1")
        self.work_group = QtWidgets.QButtonGroup(MainWindow)
        self.work_group.setObjectName("work_group")
        self.work_group.addButton(self.work1)
        self.work2 = QtWidgets.QRadioButton(self.centralwidget)
        self.work2.setGeometry(QtCore.QRect(255, 99, 70, 20))
        self.work2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.work2.setObjectName("work2")
        self.work_group.addButton(self.work2)
        self.work3 = QtWidgets.QRadioButton(self.centralwidget)
        self.work3.setGeometry(QtCore.QRect(330, 99, 70, 20))
        self.work3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.work3.setObjectName("work3")
        self.work_group.addButton(self.work3)
        self.work4 = QtWidgets.QRadioButton(self.centralwidget)
        self.work4.setGeometry(QtCore.QRect(405, 99, 70, 20))
        self.work4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.work4.setObjectName("work4")
        self.work_group.addButton(self.work4)
        self.work5 = QtWidgets.QRadioButton(self.centralwidget)
        self.work5.setGeometry(QtCore.QRect(470, 99, 70, 20))
        self.work5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.work5.setObjectName("work5")
        self.work_group.addButton(self.work5)
        self.work6 = QtWidgets.QRadioButton(self.centralwidget)
        self.work6.setGeometry(QtCore.QRect(545, 99, 70, 20))
        self.work6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.work6.setObjectName("work6")
        self.work_group.addButton(self.work6)
        self.work7 = QtWidgets.QRadioButton(self.centralwidget)
        self.work7.setGeometry(QtCore.QRect(620, 99, 70, 20))
        self.work7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);\n"
"font: 10pt \"맑은 고딕\";")
        self.work7.setObjectName("work7")
        self.work_group.addButton(self.work7)
        self.date1_ex = QtWidgets.QPushButton(self.centralwidget)
        self.date1_ex.setGeometry(QtCore.QRect(1080, 4, 30, 30))
        self.date1_ex.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);")
        self.date1_ex.setObjectName("date1_ex")
        self.date2_ex = QtWidgets.QPushButton(self.centralwidget)
        self.date2_ex.setGeometry(QtCore.QRect(1080, 34, 30, 30))
        self.date2_ex.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 69, 84);")
        self.date2_ex.setObjectName("date2_ex")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.campany, self.name)
        MainWindow.setTabOrder(self.name, self.date1)
        MainWindow.setTabOrder(self.date1, self.date2)
        MainWindow.setTabOrder(self.date2, self.date3)
        MainWindow.setTabOrder(self.date3, self.work1)
        MainWindow.setTabOrder(self.work1, self.work2)
        MainWindow.setTabOrder(self.work2, self.work3)
        MainWindow.setTabOrder(self.work3, self.work4)
        MainWindow.setTabOrder(self.work4, self.work5)
        MainWindow.setTabOrder(self.work5, self.work6)
        MainWindow.setTabOrder(self.work6, self.work7)
        MainWindow.setTabOrder(self.work7, self.ea1)
        MainWindow.setTabOrder(self.ea1, self.ea2)
        MainWindow.setTabOrder(self.ea2, self.path_create)
        MainWindow.setTabOrder(self.path_create, self.path_save)
        MainWindow.setTabOrder(self.path_save, self.date1_ex)
        MainWindow.setTabOrder(self.date1_ex, self.date2_ex)
        MainWindow.setTabOrder(self.date2_ex, self.date3_ex)
        MainWindow.setTabOrder(self.date3_ex, self.file_search)
        MainWindow.setTabOrder(self.file_search, self.reset)
        MainWindow.setTabOrder(self.reset, self.allreset)
        MainWindow.setTabOrder(self.allreset, self.printbtn)
        MainWindow.setTabOrder(self.printbtn, self.filelist)
        MainWindow.setTabOrder(self.filelist, self.create)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VPS LABEL"))
        self.date2_label.setText(_translate("MainWindow", "생산완료일"))
        self.path_create.setText(_translate("MainWindow", "생성"))
        self.work_label.setText(_translate("MainWindow", "작업구분"))
        self.file_label.setText(_translate("MainWindow", "파일"))
        self.create.setText(_translate("MainWindow", "라벨 생성"))
        self.name_label.setText(_translate("MainWindow", "작업명"))
        self.file_search.setText(_translate("MainWindow", "파일 찾기"))
        self.path_label.setText(_translate("MainWindow", "라벨저장경로"))
        self.date1_label.setText(_translate("MainWindow", "판금완료일"))
        self.ea_label.setText(_translate("MainWindow", "수량옵션"))
        self.path_save.setText(_translate("MainWindow", "저장"))
        self.company_label.setText(_translate("MainWindow", "고객사"))
        self.printbtn.setText(_translate("MainWindow", "출력"))
        self.allreset.setText(_translate("MainWindow", "전체리셋"))
        self.reset.setText(_translate("MainWindow", "파일리셋"))
        self.ea1.setText(_translate("MainWindow", "ON"))
        self.ea2.setText(_translate("MainWindow", "OFF"))
        self.date3_label.setText(_translate("MainWindow", "고객사납품일"))
        self.date3_ex.setText(_translate("MainWindow", "▼"))
        self.work1.setText(_translate("MainWindow", "공란"))
        self.work2.setText(_translate("MainWindow", "양산"))
        self.work3.setText(_translate("MainWindow", "단품"))
        self.work4.setText(_translate("MainWindow", "FR"))
        self.work5.setText(_translate("MainWindow", "긴급"))
        self.work6.setText(_translate("MainWindow", "불량"))
        self.work7.setText(_translate("MainWindow", "기타"))
        self.date1_ex.setText(_translate("MainWindow", "▼"))
        self.date2_ex.setText(_translate("MainWindow", "▼"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
